<meta name="google-site-verification" content="qp3YmDme8GAayuFPBT0W0KnEhcV_h1EDwuquUh6Hwq4" />
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4766265816301952"
     crossorigin="anonymous"></script>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4766265816301952"
     crossorigin="anonymous"></script>
<script async custom-element="amp-auto-ads"
        src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
</script>